[tools]
# =================================================================================================
# Project Tools -> pinned versions
# =================================================================================================
go = "1.25.7"
"aqua:golangci/golangci-lint" = "2.9.0"
"aqua:goreleaser/goreleaser" = "2.13.3"
"aqua:kubernetes/kubectl" = "1.33.1"


# =================================================================================================
# Misc Tools
# =================================================================================================
"aqua:kubernetes/minikube" = "latest"
"aqua:helm/helm" = "latest"
"aqua:derailed/k9s" = "latest"
direnv = "latest"


# =================================================================================================
# CI Tools
# =================================================================================================
"aqua:rhysd/actionlint" = "1"
"shellcheck" = "0.11"
svu = "latest"

# =================================================================================================
# TASKS -> GO
# =================================================================================================
[tasks."release"]
description = "Run goreleaser in snapshot mode."
run = "goreleaser release --snapshot --clean"

[tasks."lint"]
description = "Run golangci-lint in fix mode."
run = "golangci-lint run --fix"

[tasks."test"]
description = "Run e2e tests."
run = "bash scripts/test.sh"
