---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Meta - Label Sync

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Dry Run"
        default: true
        required: false
        type: boolean

  pull_request:
    paths:
      - ".github/configs/labels.yaml"
      - ".github/workflows/meta-label-sync.yaml"

  push:
    branches: ["main"]
    paths:
      - ".github/configs/labels.yaml"
      - ".github/workflows/meta-label-sync.yaml"

  schedule:
    - cron: "0 0 * * *" # Every day at midnight

jobs:
  label-sync:
    uses: mirceanton/reusable-workflows/.github/workflows/meta-label-sync.yaml@ad68966d90780c09542180ea2f598d0befc6990f
    secrets: inherit
    with:
      dry-run: ${{ inputs.dry-run || github.event_name == 'pull_request' }}
      config-file: ".github/configs/labels.yaml"
